### PR TITLE
[MRG] Adds support for updating an existing file

### LINKED ISSUE #19: Can not overwrite an existing file
`osf upload` can only create new files, if a file with the same name already exists it can't overwrite it.

The request is similar (omit name parameter), the tricky part is determining whether the user meant to overwrite the file or if it was a typo/mistake. And how to let users set this from the CLI.

### PR DESCRIPTION
**Pull request by betatim**
Fixes #19 

Gives people the ability to update an existing file.

[WIP] <- still work in progress

### CODE REVIEW

**Comment by betatim** [comment]
I think this is ready for some reviewing.

**Comment by betatim** [comment]
Actually ready for some reviewing now @gedankenstuecke or @La0

**Comment by betatim** [comment]
That doesn't matter really because travis runs on the merge of master and the PR. So as long as there are no merge conflicts we are ok.

**Comment by gedankenstuecke** [comment]
Okay, convinced! 👍

**Comment by betatim** [comment]
🎉

**Pull request merged**
