### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Tried to make the intro of the README more beginner friendly (i.e. what happens if you've no clue what OSF does). Should address #44 and #49

### CODE REVIEW

**Comment by betatim** [comment]
LGTM (looks good to me).

Ready to merge from your side?

**Comment by gedankenstuecke** [comment]
Yep! 👍

**Comment by betatim** [comment]
Sending :cake: for your lunch break!

**Comment by gedankenstuecke** [comment]
🎉  Thanks! Will make sure to get some!

**Pull request merged**
