### PR TITLE
[MRG] Add figshare as a storage provider

### PR DESCRIPTION
**Pull request by ethanwhite**
Adds one of the storage providers needed for #84.

### CODE REVIEW

**Comment by ethanwhite** [comment]
I've tested this locally and it works great.

**Comment by betatim** [comment]
Thanks! Travis is happy, I'm happy -> merge! Don't let @ctb mock you

**Comment by betatim** [comment]
Hi @ethanwhite we operate under what is often called "the pull request hack" (see #10). Basically once some of your work has been merged we add you to the list of people who can merge other's work. Would that be Ok with you?

**Comment by ethanwhite** [comment]
If @ctb didn't mock me I wouldn't know he cared :smile: 

> we operate under what is often called "the pull request hack" (see #10). Basically once some of your work has been merged we add you to the list of people who can merge other's work. Would that be Ok with you?

Yep

**Comment by betatim** [comment]
Welcome aboard ⛵️ ! With great power comes great responsibility.

**Pull request merged**
