### PR TITLE
added googledrive to storage provider

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Inspired by @ethanwhite: Another one for #84.

### CODE REVIEW

**Comment by betatim** [comment]
Did you try it with a project that has a google drive attached? If yes -> merge.

**Comment by gedankenstuecke** [comment]
I did, and it uploaded my test.txt to google drive just fine :)

**Comment by betatim** [comment]
Whoop! Does this mean your thesis is now backed up to one more place? :)

**Comment by gedankenstuecke** [comment]
Not yet ;)

**Pull request merged**
