### PR TITLE
Add long_description; fix header styling; add py36 classifier

### LINKED ISSUE #95: Better PyPI project page
Switch `setup.py` to read in the README as long description so it appears on PyPI's page for the project.

### PR DESCRIPTION
**Pull request by sloria**
closes #95

### CODE REVIEW

**Comment by betatim** [comment]
Thanks for this!

**Comment by betatim** [comment]
Hi @sloria we operate under what is often called "the pull request hack" (see #10). Basically once some of your work has been merged we add you to the list of people who can merge other's work. Would that be Ok with you?

**Comment by sloria** [comment]
@betatim Fine with me!

**Comment by betatim** [comment]
Welcome aboard!

**Pull request merged**
