### PR TITLE
add authentication options, get ls and fetch both working

### PR DESCRIPTION
**Pull request by ctb**
* adds `-u/--username`
* `python -m osfclient ls 7g6vu` and `python -m osfclient fetch 7g6vu` work as expected.

### CODE REVIEW

**Comment by ctb** [comment]
ready for review @betatim

**Comment by betatim** [comment]
(nb. you should be able to run `osf ls ...` instead of having to type out `python -m osfclient ls ...`)

**Comment by ctb** [comment]
On Mon, Mar 13, 2017 at 02:01:41AM -0700, Tim Head wrote:
> (nb. you should be able to run `osf ls ...` instead of having to type out `python -m osfclient ls ...`)

I'm running without installing it.

**Comment by betatim** [comment]
Let's build up some steam and functionality before going into too much detail on reviews.

**Comment by betatim** [comment]
by the way: `pip install -e .` for the win :)

**Pull request merged**
